# Generated by Django 4.2.7 on 2024-05-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CH', 'Chocolate'), ('ML', 'Milk'), ('IC', 'Ice-cream'), ('JU', 'Juice'), ('CA', 'Cake'), ('SW', 'Sweet'), ('BI', 'Biscuit'), ('BA', 'Baby-food'), ('FR', 'Fruits')], max_length=2),
        ),
    ]
