# Generated by Django 4.2.7 on 2024-05-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0006_remove_customer_mobile_remove_orderplaced_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('LA', 'Laptop'), ('MO', 'Mobile'), ('SO', 'Soundbox')], max_length=2),
        ),
    ]
