# Generated by Django 4.2.7 on 2024-05-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0011_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
