# Generated by Django 4.2.7 on 2024-05-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0014_rename_is_active_slider_in_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='slider',
            name='information',
        ),
    ]
