# Generated by Django 4.2.7 on 2024-05-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0016_rename_state_customer_district'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
