# Generated by Django 4.2.7 on 2024-05-27 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0018_slider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
