# Generated by Django 4.2.7 on 2024-05-31 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0021_product_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
    ]
