# Generated by Django 4.2.7 on 2024-05-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0023_slider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
